CREATE TABLE IF NOT EXISTS auto_feed_schedule (
    id INT AUTO_INCREMENT PRIMARY KEY,
    jadwal_pagi TIME NOT NULL,
    jadwal_sore TIME NOT NULL,
    status TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
